/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Conexão.Conexao;
import SQL.AuthorsDAO;
import SQL.BooksDAO;
import SQL.PublishersDAO;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Author;
import model.AuthorBD;
import model.Book;
import model.BookBD;
import model.Publisher;
import model.PublisherBD;

/**
 *
 * @author sandy
 */
public class Tela_de_modificar_o_banco extends javax.swing.JFrame {

    /**
     * Creates new form Tela_de_modificar_o_banco
     */
    public Tela_de_modificar_o_banco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        nome_do_livro_bd = new javax.swing.JTextField();
        Numero_do_livro_bd = new javax.swing.JTextField();
        preco_bd = new javax.swing.JTextField();
        nome_do_autor_bd = new javax.swing.JTextField();
        sobrenome_do_autor_bd = new javax.swing.JTextField();
        nome_da_editora_bd = new javax.swing.JTextField();
        url_bd = new javax.swing.JTextField();
        preco_atual = new javax.swing.JTextField();
        numero_do_livro_atual = new javax.swing.JTextField();
        nome_do_autor_atual = new javax.swing.JTextField();
        Sobrenome_do_autor_atual = new javax.swing.JTextField();
        nome_do_livro_atual = new javax.swing.JTextField();
        nome_da_editora_atual = new javax.swing.JTextField();
        URL_atual = new javax.swing.JTextField();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nome do livro :");

        jLabel3.setText("Nome atual do livro :");

        jLabel4.setText("Numero do livro: ");

        jLabel5.setText("Como está no banco:");

        jLabel6.setText("Preço do livro: ");

        jLabel8.setText("Nome do autor:");

        jLabel7.setText("Sobrenome do autor: ");

        jLabel9.setText("Nome da editora:");

        jLabel10.setText("URL da editora:");

        jLabel11.setText("Modificações que tem que ser feitas");

        jLabel12.setText("Numero do livro: ");

        jLabel13.setText("Preço do livro: ");

        jLabel14.setText("Nome do autor:");

        jLabel15.setText("Sobrenome do autor: ");

        jLabel16.setText("Nome da editora:");

        jLabel17.setText("URL da editora:");

        Modificar.setText("Modificar->>");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        nome_do_livro_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_do_livro_bdActionPerformed(evt);
            }
        });

        Numero_do_livro_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero_do_livro_bdActionPerformed(evt);
            }
        });

        nome_do_autor_bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_do_autor_bdActionPerformed(evt);
            }
        });

        nome_do_autor_atual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_do_autor_atualActionPerformed(evt);
            }
        });

        nome_do_livro_atual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_do_livro_atualActionPerformed(evt);
            }
        });

        URL_atual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URL_atualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel11)))
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome_do_livro_bd)
                                    .addComponent(Numero_do_livro_bd)
                                    .addComponent(preco_bd)
                                    .addComponent(nome_do_autor_bd)
                                    .addComponent(sobrenome_do_autor_bd)
                                    .addComponent(nome_da_editora_bd)
                                    .addComponent(url_bd, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(preco_atual, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numero_do_livro_atual)
                                    .addComponent(nome_do_autor_atual)
                                    .addComponent(nome_do_livro_atual)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sobrenome_do_autor_atual)
                                    .addComponent(nome_da_editora_atual)
                                    .addComponent(URL_atual))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Modificar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nome_do_livro_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Numero_do_livro_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(preco_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_do_autor_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sobrenome_do_autor_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nome_da_editora_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(url_bd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_do_livro_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(numero_do_livro_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preco_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_do_autor_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Sobrenome_do_autor_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nome_da_editora_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(URL_atual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Modificar)
                .addGap(176, 176, 176))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_do_livro_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_do_livro_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_do_livro_bdActionPerformed

    private void Numero_do_livro_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero_do_livro_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Numero_do_livro_bdActionPerformed

    private void nome_do_autor_atualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_do_autor_atualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_do_autor_atualActionPerformed

    private void nome_do_livro_atualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_do_livro_atualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_do_livro_atualActionPerformed

    private void URL_atualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URL_atualActionPerformed
        // TODO add your hangdling code here:
    }//GEN-LAST:event_URL_atualActionPerformed

    private void nome_do_autor_bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_do_autor_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_do_autor_bdActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        String nome_livro_bd=nome_do_livro_bd.getText();
        String numero_livro_bd=Numero_do_livro_bd.getText();
        String precobd=preco_bd.getText();
        float prebd=Float.parseFloat(precobd);
        
        String nome_autor_bd=nome_do_autor_bd.getText();
        String sobrenome_autor_bd=sobrenome_do_autor_bd.getText();
        
        String nome_editora_bd=nome_da_editora_bd.getText();
        String urlbd=url_bd.getText();
        
        String nome_livro_atual=nome_do_livro_atual.getText();
        String numero_livro_atual=numero_do_livro_atual.getText();
        String precoatual=preco_atual.getText();
        float preatual=Float.parseFloat(precoatual);
        
        String nome_autor_atual=nome_do_autor_atual.getText();
        String Sobrenome_autor_atual=Sobrenome_do_autor_atual.getText();
        
        String nome_editora_atual=nome_da_editora_atual.getText();
        String URLatual=URL_atual.getText();
        
        Book livro=new Book(nome_livro_atual,numero_livro_atual,preatual);
        BookBD bdL=new BookBD(nome_livro_bd, numero_livro_bd,prebd);
        Author autor=new  Author(nome_autor_atual,Sobrenome_autor_atual);
        AuthorBD bdA= new AuthorBD(nome_autor_bd,sobrenome_autor_bd);
        Publisher editora=new Publisher(nome_editora_atual, URLatual);
        PublisherBD BDp =new PublisherBD(nome_editora_bd,urlbd);
        try {
            Connection conexao=new Conexao().getConnection();
            BooksDAO livros=new BooksDAO(conexao);
            PublishersDAO editoras =new PublishersDAO(conexao);
            AuthorsDAO autores=new AuthorsDAO(conexao);
            autores.modificar(autor,bdA);
            editoras.modificar(editora,BDp);
            livros.modificar(livro,bdL);
            JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "[ERRO] Registro não  foi salvo");
            System.err.println("[ERRO]"+ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "[ERRO] Registro não  foi salvo");
            System.err.println("[ERRO]"+ex);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_de_modificar_o_banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_de_modificar_o_banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_de_modificar_o_banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_de_modificar_o_banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_de_modificar_o_banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Numero_do_livro_bd;
    private javax.swing.JTextField Sobrenome_do_autor_atual;
    private javax.swing.JTextField URL_atual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField nome_da_editora_atual;
    private javax.swing.JTextField nome_da_editora_bd;
    private javax.swing.JTextField nome_do_autor_atual;
    private javax.swing.JTextField nome_do_autor_bd;
    private javax.swing.JTextField nome_do_livro_atual;
    private javax.swing.JTextField nome_do_livro_bd;
    private javax.swing.JTextField numero_do_livro_atual;
    private javax.swing.JTextField preco_atual;
    private javax.swing.JTextField preco_bd;
    private javax.swing.JTextField sobrenome_do_autor_bd;
    private javax.swing.JTextField url_bd;
    // End of variables declaration//GEN-END:variables
}
